import = [
    "~/.config/alacritty/catpuccin-macchiato.toml"
]

shell = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.8

[font]
size = 10
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[mouse]
hide_when_typing = true
